[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib @ ^7.7.1
    mandulaj/PZEM-004T-v30 @ ^1.1.2
